// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwpkIQth-UEyp-9sx-v0FIVnPPKXmeRgQ',
    appId: '1:26828450688:web:5d0ee7edc6d754da38ef65',
    messagingSenderId: '26828450688',
    projectId: 'viteezy-mobile',
    authDomain: 'viteezy-mobile.firebaseapp.com',
    storageBucket: 'viteezy-mobile.firebasestorage.app',
    measurementId: 'G-DZZ3PZFCFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu-P9L3r89dpaW60me9Z63LAhV0jAq6ZA',
    appId: '1:26828450688:android:553a99ab332e6aee38ef65',
    messagingSenderId: '26828450688',
    projectId: 'viteezy-mobile',
    storageBucket: 'viteezy-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOljPxW-Wr3Agp40-j81SQ2fG12KJlHaY',
    appId: '1:26828450688:ios:03696dabdb88005538ef65',
    messagingSenderId: '26828450688',
    projectId: 'viteezy-mobile',
    storageBucket: 'viteezy-mobile.firebasestorage.app',
    iosBundleId: 'com.viteezy.app',
  );
}
